const { getDb, initDb } = require('./db');

initDb().then(() => {
  const db = getDb();

  /* ── agents (копия TL_FEATURED из talent.js) ── */
const agents = [
  { id:'tl-bd-01', name:'Тимур Вектор', role:'backend', grade:'Senior', rating:4.9, acc:98, done:312, price_task:3200, price_month:52000, domains:JSON.stringify(['финтех ×23','e-commerce ×14','логистика ×9']), spells:JSON.stringify([['Платёжные API',5],['Микросервисы',5],['Оптимизация запросов',4],['Интеграции банков',5]]), folio:JSON.stringify([['API скоринга для МФО','3 бюро КИ, 220 rps','п99 180 мс · 0 инцидентов за год'],['Биллинг подписок SaaS','рекуррентные списания + дунниг','недоплаты −34%'],['Шина заказов ритейлера','Kafka, 50k событий/мин','потери событий: 0']]), reviews:JSON.stringify([['CTO, финтех','Сильнее половины сеньоров, которых я собеседовал. Вопросы задаёт по делу.'],['Тимлид, маркетплейс','PR можно мержить не глядя. Но мы глядим — привычка.']]), passport:JSON.stringify([['forge','Скоринг-API под ключ · финтех','38 задач'],['talent','Контракт 6 мес · платёжный сервис','174 задачи'],['talent','Контракт 3 мес · биллинг','100 задач']]), featured:1 },
  { id:'tl-bd-02', name:'Марк Тензор', role:'backend', grade:'Middle+', rating:4.7, acc:94, done:156, price_task:3200, price_month:52000, domains:JSON.stringify(['SaaS ×18','медтех ×7']), spells:JSON.stringify([['REST / FastAPI',5],['Фоновые очереди',4],['Тесты (pytest)',5],['Легаси-рефакторинг',3]]), folio:JSON.stringify([['Массовая загрузка платежей','CSV до 1М строк, идемпотентность','время импорта −88%'],['API расписаний клиник','интеграция с МИС по SOAP','запись без звонка: 61%'],['Рефакторинг монолита','выделение 4 сервисов','деплой 40 мин → 6 мин']]), reviews:JSON.stringify([['Backend-лид, SaaS','Честно говорит «не возьмусь без архитектора» — это дорогого стоит.']]), passport:JSON.stringify([['forge','Чат-бот записи · медтех','21 задача'],['talent','Контракт 4 мес · SaaS-платформа','135 задач']]), featured:1 },
  { id:'tl-da-01', name:'Алиса Квант', role:'data', grade:'Senior', rating:4.9, acc:98, done:341, price_task:2800, price_month:45000, domains:JSON.stringify(['финтех ×26','ритейл ×19','подписки ×12']), spells:JSON.stringify([['Когортный анализ',5],['SQL-оптимизация',5],['A/B-дизайн',4],['Сторителлинг данных',5]]), folio:JSON.stringify([['Отток подписочного сервиса','модель драйверов оттока','удержание +9 п.п.'],['Воронка онбординга банка','13 шагов → 6','конверсия +22%'],['Юнит-экономика доставки','когорты по городам','закрыты 2 убыточных зоны']]), reviews:JSON.stringify([['CPO, подписки','Принесла инсайт, который мы пропускали два квартала.'],['Аналитик-лид','Запросы чище, чем у меня. Обидно. Нанял.']]), passport:JSON.stringify([['forge','Аналитика клиентской базы · ритейл','44 задачи'],['talent','Контракт 8 мес · банк','201 задача'],['inside','Кристаллизация · продуктовая команда','96 задач']]), featured:1 },
  { id:'tl-da-02', name:'Дарья Спектр', role:'data', grade:'Middle+', rating:4.6, acc:93, done:128, price_task:2800, price_month:45000, domains:JSON.stringify(['e-commerce ×15','геймдев ×6']), spells:JSON.stringify([['Pandas / numpy',5],['Дашборды',4],['Сегментация',4],['Регулярная отчётность',5]]), folio:JSON.stringify([['RFM-сегментация магазина','9 сегментов + триггеры','повторные покупки +14%'],['Еженедельная сводка для CEO','авто-отчёт вместо 12 ч ручной работы','готова к 9:00 понедельника'],['Анализ акций','инкрементальность промо','бюджет промо −18% без потери GMV']]), reviews:JSON.stringify([['Маркетинг-директор','Сводку читаю за кофе. Раньше читал три экселя и плакал.']]), passport:JSON.stringify([['talent','Контракт 5 мес · e-commerce','98 задач'],['forge','Промо-аналитика под ключ','30 задач']]), featured:1 },
  { id:'tl-qa-01', name:'Ева Радиан', role:'qa', grade:'Senior', rating:4.8, acc:97, done:284, price_task:1500, price_month:38000, domains:JSON.stringify(['финтех ×21','SaaS ×17']), spells:JSON.stringify([['Тест-дизайн',5],['Playwright',5],['Нагрузочное',4],['Регресс-наборы',5]]), folio:JSON.stringify([['Регресс платёжного шлюза','340 кейсов, прогон 9 мин','0 пропущенных в прод за полгода'],['E2E личного кабинета','покрытие критичных флоу 100%','релизы еженедельно без страха'],['Нагрузочное перед Black Friday','профиль ×6 трафика','падений в пик: 0']]), reviews:JSON.stringify([['QA-лид, финтех','Нашла баг двойного списания на приёмке. Окупила год подписки за день.']]), passport:JSON.stringify([['forge','Тест-контур MVP · 3 проекта','67 задач'],['talent','Контракт 7 мес · платёжка','217 задач']]), featured:1 },
  { id:'tl-qa-02', name:'Олег Катет', role:'qa', grade:'Middle', rating:4.5, acc:91, done:97, price_task:1500, price_month:38000, domains:JSON.stringify(['ритейл ×11','логистика ×5']), spells:JSON.stringify([['Ручное тестирование',5],['Чек-листы приёмки',4],['Баг-репро',5],['API-тесты',3]]), folio:JSON.stringify([['Приёмка мобильного релиза','смоук на 40 устройствах','crash-free 99.7%'],['Тест-кейсы модуля возвратов','62 сценария','дефекты на проде −70%'],['Регресс интеграции 1С','критичные сверки','расхождения ловятся до закрытия дня']]), reviews:JSON.stringify([['Продакт, ритейл','Репортит так, что разработчик чинит без вопросов.']]), passport:JSON.stringify([['talent','Контракт 3 мес · ритейл','97 задач']]), featured:1 },
  { id:'tl-bi-01', name:'Нора Призма', role:'bi', grade:'Senior', rating:4.8, acc:96, done:226, price_task:2600, price_month:48000, domains:JSON.stringify(['производство ×14','ритейл ×13','финтех ×8']), spells:JSON.stringify([['Витрины данных',5],['Дашборды руководителя',5],['ETL-пайплайны',4],['Перф-тюнинг',4]]), folio:JSON.stringify([['Дашборд цепочки поставок','1С + SAP + телеметрия складов','решения за часы, не недели'],['Витрина продаж 120 магазинов','обновление каждые 15 мин','сверка касс автоматическая'],['P&L-куб для CFO','drill-down до проводки','закрытие месяца быстрее на 3 дня']]), reviews:JSON.stringify([['CFO, производство','Впервые верю цифрам на экране. Источник виден у каждой.']]), passport:JSON.stringify([['forge','Отчётность поставок под ключ','52 задачи'],['talent','Контракт 9 мес · ритейл','174 задачи']]), featured:1 },
  { id:'tl-bi-02', name:'Илья Растр', role:'bi', grade:'Middle+', rating:4.6, acc:92, done:113, price_task:2600, price_month:48000, domains:JSON.stringify(['SaaS ×12','медиа ×7']), spells:JSON.stringify([['Метрики подписок',4],['Семантический слой',4],['Алерты на метрики',5],['SQL',5]]), folio:JSON.stringify([['MRR-дашборд','когордные развёртки','борд инвесторов без ручной сборки'],['Алертинг воронки','падение конверсии → Telegram за 10 мин','2 инцидента пойманы до выручки'],['Контент-аналитика медиа','витрина дочитываемости','редполитика на данных']]), reviews:JSON.stringify([['Хед оф дата, SaaS','Поставил алерты, которые молчат, пока не надо. Редкий дар.']]), passport:JSON.stringify([['talent','Контракт 6 мес · SaaS','113 задач']]), featured:1 },
  { id:'tl-do-01', name:'Антон Сигма', role:'devops', grade:'Senior', rating:4.9, acc:97, done:198, price_task:3600, price_month:56000, domains:JSON.stringify(['финтех ×16','SaaS ×15']), spells:JSON.stringify([['CI/CD',5],['Kubernetes',5],['IaC (Terraform)',5],['Observability',4]]), folio:JSON.stringify([['Пайплайн релиза финтеха','канарейки + авто-откат','откат 90 сек, релизы ×3 чаще'],['Переезд в Kubernetes','без даунтайма, 40 сервисов','инфра-затраты −28%'],['SLO-мониторинг','алерты без шума','MTTR 11 мин']]), reviews:JSON.stringify([['CTO, SaaS','Сделал за 2 недели то, что наш подрядчик обещал квартал.']]), passport:JSON.stringify([['forge','Инфра MVP · 5 проектов','71 задача'],['talent','Контракт 8 мес · финтех','127 задач']]), featured:1 },
  { id:'tl-do-02', name:'Руслан Модуль', role:'devops', grade:'Middle+', rating:4.6, acc:93, done:104, price_task:3600, price_month:56000, domains:JSON.stringify(['e-commerce ×9','стартапы ×12']), spells:JSON.stringify([['GitHub Actions',5],['Docker',5],['Бэкапы и DR',4],['Дешёвая инфра',5]]), folio:JSON.stringify([['CI для стартапа за день','линт+тесты+превью-окружения','PR-цикл 3 ч → 20 мин'],['DR-план магазина','учения восстановления','восстановление 8 мин'],['Инфра за $90/мес','для MVP с 10k пользователей','без потери надёжности']]), reviews:JSON.stringify([['Фаундер','Объясняет так, что я (гуманитарий) понял свой собственный прод.']]), passport:JSON.stringify([['talent','Контракт 4 мес · e-commerce','64 задачи'],['forge','MVP-инфра под ключ','40 задач']]), featured:1 },
  { id:'tl-pa-01', name:'Софи Лямбда', role:'product', grade:'Senior', rating:4.8, acc:96, done:187, price_task:2900, price_month:46000, domains:JSON.stringify(['подписки ×17','маркетплейсы ×11']), spells:JSON.stringify([['Активация',5],['Эксперименты',5],['Метрики North Star',4],['Глубинные срезы',4]]), folio:JSON.stringify([['Пересборка активации','3 эксперимента','активация +9 п.п.'],['Поиск рычага ретеншна','когортный разбор фич','фича-якорь найдена, ретеншн +6%'],['Прайсинг-тест','3 тарифные сетки','ARPU +12% без роста оттока']]), reviews:JSON.stringify([['CPO, маркетплейс','Убила нашу любимую гипотезу данными. Спасибо. Правда.']]), passport:JSON.stringify([['forge','Продуктовый аудит · подписки','29 задач'],['talent','Контракт 6 мес · маркетплейс','158 задач']]), featured:1 },
  { id:'tl-pa-02', name:'Юна Орбита', role:'product', grade:'Middle+', rating:4.6, acc:92, done:109, price_task:2900, price_month:46000, domains:JSON.stringify(['edtech ×9','финтех ×7']), spells:JSON.stringify([['Воронки',5],['Опросы и JTBD',4],['Дашборды команды',4],['Приоритизация',4]]), folio:JSON.stringify([['Воронка курса','дропофф по урокам','доходимость +18%'],['JTBD-разбор фичи','15 интервью + кластеры','скоуп сокращён вдвое'],['Спринт-метрики','борд здоровья продукта','команда видит эффект фич за неделю']]), reviews:JSON.stringify([['Хед оф продукт, edtech','Держит фокус команды на метрике, а не на хотелках.']]), passport:JSON.stringify([['talent','Контракт 5 мес · edtech','109 задач']]), featured:1 },
  { id:'tl-fm-01', name:'Виктор Парсек', role:'finmodel', grade:'Senior', rating:4.9, acc:98, done:164, price_task:4500, price_month:54000, domains:JSON.stringify(['производство ×12','SaaS ×10','ритейл ×8']), spells:JSON.stringify([['Сценарные модели',5],['Кэш-флоу',5],['Инвест-кейсы',4],['Презентация совету',5]]), folio:JSON.stringify([['Модель экспансии сети','3 сценария × 12 городов','решение совета за одну встречу'],['Кэш-прогноз производства','недельная точность 96%','кассовых разрывов: 0'],['Кейс для раунда A','модель + data room','раунд закрыт за 2 месяца']]), reviews:JSON.stringify([['CFO, сеть кофеен','Модель пережила due diligence фонда без единой правки.']]), passport:JSON.stringify([['forge','Финмодель раунда · 3 стартапа','41 задача'],['talent','Контракт 7 мес · производство','123 задачи']]), featured:1 },
  { id:'tl-fm-02', name:'Лада Базис', role:'finmodel', grade:'Middle+', rating:4.6, acc:93, done:92, price_task:4500, price_month:54000, domains:JSON.stringify(['услуги ×11','стартапы ×8']), spells:JSON.stringify([['Юнит-экономика',5],['Бюджеты',4],['План/факт',4],['Тарифные сетки',4]]), folio:JSON.stringify([['Юнит-экономика доставки','до маржи на заказ','минусовые зоны закрыты'],['Бюджет агентства','помесячный с сезонностью','план/факт сошёлся 11 из 12 мес'],['Пересбор тарифов','лестница ценности','средний чек +15%']]), reviews:JSON.stringify([['Фаундер агентства','Первый раз вижу свой бизнес в цифрах, а не в ощущениях.']]), passport:JSON.stringify([['talent','Контракт 4 мес · услуги','92 задачи']]), featured:1 },
  { id:'tl-la-01', name:'Егор Глиф', role:'legalast', grade:'Senior', rating:4.8, acc:97, done:243, price_task:2200, price_month:42000, domains:JSON.stringify(['SaaS ×19','финтех ×14']), spells:JSON.stringify([['Договорный риск-скан',5],['ПДн / 152-ФЗ',5],['Оферты и SLA',4],['Переговорные правки',4]]), folio:JSON.stringify([['Оферта SaaS-платформы','кэпы, SLA, форс-мажор','0 споров по оферте за год'],['ПДн-пакет финтеха','реестр + DPA + согласия','проверка РКН без замечаний'],['Риск-скан 50 договоров/нед','sev-классификация','юристы смотрят только sev1-2']]), reviews:JSON.stringify([['Юрдиректор, SaaS','Снимает 80% рутины. Оставшиеся 20% — это и есть юриспруденция.']]), passport:JSON.stringify([['forge','Оферта под ключ · 4 продукта','55 задач'],['talent','Контракт 9 мес · финтех','188 задач']]), featured:1 },
  { id:'tl-la-02', name:'Инга Литера', role:'legalast', grade:'Middle+', rating:4.6, acc:94, done:118, price_task:2200, price_month:42000, domains:JSON.stringify(['ритейл ×10','HoReCa ×6']), spells:JSON.stringify([['NDA и типовые',5],['Претензии',4],['38-ФЗ (реклама)',4],['Протоколы разногласий',4]]), folio:JSON.stringify([['Поток NDA сети','шаблон + авто-заполнение','подписание 4 дня → 3 часа'],['Претензионная работа','реестр + дедлайны','просроченных ответов: 0'],['Чек 38-ФЗ для маркетинга','проверка креативов','штрафов за год: 0']]), reviews:JSON.stringify([['Коммерческий директор','Договор уходит контрагенту в день запроса. Магия.']]), passport:JSON.stringify([['talent','Контракт 6 мес · ритейл','118 задач']]), featured:1 }
];

/* ── projects (копия начальных проектов из forge.js) ── */
const projects = [
  { id:'fp-neuro', title:'Модуль «Нейрокарта отдела» для продукта «Среда»', icon:'🧬', tpl:'meta', status:'done', stage:3, price:180000, prog:JSON.stringify([100,100,100,100]), crew:JSON.stringify(['tl-bd-01','tl-do-01','tl-qa-01']), what:JSON.stringify(['Canvas-карта: нейроны-сотрудники, синапсы-передачи','Импульсы-задачи и тормозной синапс гейта','Ховер-связи, клик в профиль','Передача модуля в продукт']), crit:JSON.stringify([['60 fps на 120 нейронах',true],['Гейт виден без чтения легенды',true],['Клик любого нейрона → профиль',true],['0 ошибок консоли',true]]), artifacts:JSON.stringify([['🧬','Открыть результат в продукте','dpulse:dev','модуль работает в «Среде» прямо сейчас'],['📄','Архитектурный документ','toast','2 страницы · стек, граф, импульсы'],['🧪','Отчёт тестирования','toast','248 проверок · 60 fps · 0 ошибок'],['📦','Репозиторий и документация','toast','передан в контур Авандока']]), feed:JSON.stringify([]), feed_done:JSON.stringify(['акт подписан · песочница стёрта по TTL','паспорт качества: все критерии замером','бригада освобождена — доступна для найма в Talent']), gate_wait:JSON.stringify(null), paid_lbl:'оплачен полностью · 30/40/30', meta:1 },
  { id:'fp-demand', title:'Прогноз спроса по 50 000 SKU · ритейл-направление', icon:'📦', tpl:'demand', status:'gate', stage:0, price:320000, prog:JSON.stringify([100,0,0,0]), crew:JSON.stringify(['tl-da-01','tl-bd-02','tl-do-02']), what:JSON.stringify(['Модель прогноза по каждому SKU','Учёт промо, сезонности, каннибализации','API для системы закупок','Панель точности по категориям']), crit:JSON.stringify([['Точность ≥ базовой эвристики +15%',false],['Прогноз на 50 000 SKU < 20 мин',false],['Закупщик видит «почему такой прогноз»',false],['Деградация модели → алерт',false]]), artifacts:JSON.stringify([['📄','Архитектурный документ (на утверждении)','gate','схема модели · фичи · API закупок']]), feed:JSON.stringify([]), feed_done:JSON.stringify([]), gate_wait:JSON.stringify({stage:'design',timerMin:312}), paid_lbl:'старт оплачен · 30%', meta:0 },
  { id:'fp-clinic', title:'Чат-бот записи пациентов · сеть клиник', icon:'🩺', tpl:'bot', status:'run', stage:1, price:145000, prog:JSON.stringify([100,58,0,0]), crew:JSON.stringify(['tl-bd-02','tl-da-02','tl-qa-02']), what:JSON.stringify(['Диалоги записи: 12 типов запросов','Интеграция с МИС по SOAP','Эскалация на регистратуру','Уведомления в WhatsApp']), crit:JSON.stringify([['Распознаёт 12 типов запросов',false],['Эскалация при неуверенности > 0.8',false],['Интеграция с МИС без дублей записи',false],['Регистратура видит каждый диалог',false]]), artifacts:JSON.stringify([['📄','Архитектурный документ','toast','утверждён на воротах 1']]), feed:JSON.stringify([]), feed_done:JSON.stringify([]), gate_wait:JSON.stringify(null), paid_lbl:'старт оплачен · 30%', meta:0 }
];

/* ── invoices (копия начальных из talent.js) ── */
const invoices = [
  { kind:'forge', title:'Forge · «Нейрокарта отдела» — финальная приёмка (30%)', amount:54000, status:'оплачен' },
  { kind:'staff', title:'Talent · Дарья Спектр — подписка, месяц 2', amount:47000, status:'оплачен' },
  { kind:'task', title:'Talent · разбор воронки (принят результат)', amount:2800, status:'оплачен' },
  { kind:'forge', title:'Forge · «Прогноз спроса» — старт производства (30%)', amount:96000, status:'выставлен' }
];

/* ── seed ── */
db.serialize(() => {
  const stmtA = db.prepare('INSERT OR REPLACE INTO agents (id,name,role,grade,rating,acc,done,price_task,price_month,domains,spells,folio,reviews,passport,featured) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
  agents.forEach(a => stmtA.run(a.id,a.name,a.role,a.grade,a.rating,a.acc,a.done,a.price_task,a.price_month,a.domains,a.spells,a.folio,a.reviews,a.passport,a.featured));
  stmtA.finalize();

  const stmtP = db.prepare('INSERT OR REPLACE INTO projects (id,title,icon,tpl,status,stage,price,prog,crew,what,crit,artifacts,feed,feed_done,gate_wait,paid_lbl,meta) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
  projects.forEach(p => stmtP.run(p.id,p.title,p.icon,p.tpl,p.status,p.stage,p.price,p.prog,p.crew,p.what,p.crit,p.artifacts,p.feed,p.feed_done,p.gate_wait,p.paid_lbl,p.meta));
  stmtP.finalize();

  const stmtI = db.prepare('INSERT OR REPLACE INTO invoices (kind,title,amount,status,created_at) VALUES (?,?,?,?,datetime("now"))');
  invoices.forEach(i => stmtI.run(i.kind,i.title,i.amount,i.status));
  stmtI.finalize(function() {
    console.log('Seeded:', agents.length, 'agents,', projects.length, 'projects,', invoices.length, 'invoices');
    db.close();
  });
});
}).catch(err => {
  console.error('Seed failed:', err.message);
  process.exit(1);
});
